apiVersion: v1
kind: ConfigMap

metadata:
  name: user-management-config
  namespace: user-management

data:

  SPRING_DATASOURCE_HOST: postgres-service

  SPRING_DATASOURCE_PORT: "5432"

  SPRING_DATASOURCE_DATABASE: user_management

  SPRING_DATASOURCE_USERNAME: postgres

  SPRING_JPA_HIBERNATE_DDL_AUTO: update

  SERVER_PORT: "8080"

  SPRING_PROFILES_ACTIVE: minikube