spring.application.name=user-management

spring.datasource.url=jdbc:postgresql://localhost:5432/user_management
spring.datasource.username=shapathisudhakarreddy
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080